services:
  vaultwarden:
    image: vaultwarden/server:1.37.3
    container_name: vaultwarden
    restart: unless-stopped

    environment:
      DOMAIN: "https://vault.tygmcd.com"

    volumes:
      - /srv/vaultwarden/data:/data

    ports:
      - "127.0.0.1:8080:80"